### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by johnpaulmedina** [64robots/nova-date-filter#7]
Throws JS error on selecting input

**Comment by johnpaulmedina** [comment]
Laravel 5.7.12
Nova 1.1.7

<img width="637" alt="screenshot 2018-10-30 12 41 44" src="https://user-images.githubusercontent.com/1139439/47734949-d0457d00-dc41-11e8-9bd2-d8a05d9c34e5.png">

Only Shows From Date

When selecting a date twice it does not throw the error any more
Apply's a very small URL attribute that does not match other formats I see with filters

?leads_page=1&leads_filter=dW5kZWZpbmVk

I usually see the filter much longer

**Comment by disitec** [comment]
Same version as you and I cant reproduce this issue. Could you provide a detailed reproduction?

**Comment by disitec** [comment]
I'm courious about this because #6 had the same problem

**Comment by wfeller** [comment]
Hi,

I'm getting the same issue:
Laravel 5.7.12
Nova 1.1.7

I tried all the releases of your package: 0.2.0, 0.1.1, 0.1.0, 0.0.2, and 0.0.1, and I always get the same problem as described above.

**Comment by johnpaulmedina** [comment]
Im wondering if there is a conflicting package or if the local version is different than the dist ?

**Comment by koss-shtukert** [comment]
Hi,
the same:
Laravel 5.7.12
Nova 1.1.7

+UI issue
![image](https://user-images.githubusercontent.com/709096/47918464-5a494c00-deb5-11e8-8f71-9c99f5f670fb.png)

**Comment by johnpaulmedina** [comment]
I believe that the JS to update the URL is what is causing the issue. No matter what is selected when you look at the URL params that are usually encoded to pass back to the API they are not correct. Which is why it can not be converted to valid JSON and which is possibly leading to throwing this exception.

**Comment by robmpreston** [comment]
We're a bit busy right now but will accept a PR if someone wants to look at it

**Comment by bomshteyn** [comment]
The issue is due to Nova changing the default select filter

We have fixed both of these issues on our branch here: https://github.com/treeStoneIT/nova-date-filter/commits/searchable-filter

**Comment by disitec** [comment]
Awesome. Could you submit a PR? I would merge it if solves the problem.

Thanks!

**Comment by MedElHeni** [comment]
I have the same issue

**Comment by disitec** [comment]
Just released `0.3.0` with changes proposed by @bomshteyn Can you confirm that issue has been resolved?

**Comment by niladam** [comment]
@disitec - The issue is still there.

<img width="289" alt="screenshot 2018-11-08 17 16 24" src="https://user-images.githubusercontent.com/4151765/48207763-0ab5c500-e37a-11e8-89f8-4062cd9908c1.png">

**Comment by bomshteyn** [comment]
@niladam It seems you have a cached version of the css.

P.S. @disitec thanks!

**Comment by niladam** [comment]
@bomshteyn -- no. Not really.

What i did was i even went to the vendor folder -- ran `npm install` and also ran `npm run production` - so no, not really a cached CSS.

**Comment by disitec** [comment]
You don’t have to do that. Package has build files. Just update your package.json to version ^0.3

**Comment by niladam** [comment]
I know i don't have to do that, but i thought it was an issue so i tried this as well.

I did. My composer.json clearly is using ^0.3.

**Comment by disitec** [comment]
Can you do a hard refresh? Ctrl + shift + r in chrome.

**Comment by niladam** [comment]
@disitec - you think i'd be wasting your time with nonsense ?:) Of course i did. And it shouldn't have any effect anyways, as i'm always with my console open..

**Comment by bomshteyn** [comment]
What does `resources/airbnb-modified.css` line 16 say?

**Comment by niladam** [comment]
It says: `width: 307.875px;`

**Comment by bomshteyn** [comment]
thats wrong, means you are on wrong version

**Comment by niladam** [comment]
If you look at [airbnb-modified.css#L16](https://github.com/64robots/nova-date-filter/blob/master/resources/airbnb-modified.css#L16) you'll notice that it's different.

**Comment by niladam** [comment]
Let me remove the package and reinstall it.

**Comment by niladam** [comment]
I reinstalled the package and tried using an `incognito` tab with Chrome. To same effect.

Now the line 16 says: `width: 264px;`

**Comment by niladam** [comment]
If you compare [@treeStoneIT/nova-date-filter/blob/master/resources/airbnb-modified.css#L16](https://github.com/treeStoneIT/nova-date-filter/blob/master/resources/airbnb-modified.css#L16) with [@64robots/nova-date-filter/blob/master/resources/airbnb-modified.css#L16](https://github.com/64robots/nova-date-filter/blob/master/resources/airbnb-modified.css#L16) you will notice they're both different.

**Comment by disitec** [comment]
They did the update in a branch different to master
